# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nd < Formula
  desc "Coding agent asset management CLI tool"
  homepage "https://github.com/armstrongl/nd"
  version "0.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/armstrongl/nd/releases/download/v0.6.0/nd_0.6.0_darwin_amd64.tar.gz"
      sha256 "22731092ca0acf65f49b7873f84f1af7267b4c82b8bbed62ad7b266c50c3a0f7"

      define_method(:install) do
        bin.install "nd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/armstrongl/nd/releases/download/v0.6.0/nd_0.6.0_darwin_arm64.tar.gz"
      sha256 "8d85d639e6863a9c4f80185400ef1ea6a9907d12339f09f5fadbab29bcd84bab"

      define_method(:install) do
        bin.install "nd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/armstrongl/nd/releases/download/v0.6.0/nd_0.6.0_linux_amd64.tar.gz"
      sha256 "ba40dba7314ab4e1578050baa95a991a5b17c149451daeadc7f68409e9c1fab8"
      define_method(:install) do
        bin.install "nd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/armstrongl/nd/releases/download/v0.6.0/nd_0.6.0_linux_arm64.tar.gz"
      sha256 "a3a6a76ab20b75740778f01d2f352e1b8cf06671b355d6724d267019dfff2bf9"
      define_method(:install) do
        bin.install "nd"
      end
    end
  end
end
