# This file was generated by GoReleaser. DO NOT EDIT.
cask "nd" do
  name "nd"
  desc "Coding agent asset management CLI tool"
  homepage "https://github.com/armstrongl/nd"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nd"

  on_macos do
    on_intel do
      url "https://github.com/armstrongl/nd/releases/download/v#{version}/nd_#{version}_darwin_amd64.tar.gz"
      sha256 "3bde956cc12e1f903d047965aa84c57b31964694da6289681e2aa748862bc092"
    end
    on_arm do
      url "https://github.com/armstrongl/nd/releases/download/v#{version}/nd_#{version}_darwin_arm64.tar.gz"
      sha256 "9e97605ae75e86e29456012b271e1f563a1ad37f06cb231daac5feaa8f94b1fd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/armstrongl/nd/releases/download/v#{version}/nd_#{version}_linux_amd64.tar.gz"
      sha256 "675a4c0906a87bf1402ba87194bd840aabaeb90e3d24b623d7a159883b7bfca2"
    end
    on_arm do
      url "https://github.com/armstrongl/nd/releases/download/v#{version}/nd_#{version}_linux_arm64.tar.gz"
      sha256 "2948cb44b181b3962ffb817731a3b908fa38b96c8e3446664e840df3abc73b72"
    end
  end

  # No zap stanza required
end
