# This file was generated by GoReleaser. DO NOT EDIT.
cask "nd" do
  name "nd"
  desc "Coding agent asset management CLI tool"
  homepage "https://github.com/armstrongl/nd"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nd"

  on_macos do
    on_intel do
      url "https://github.com/armstrongl/nd/releases/download/v#{version}/nd_#{version}_darwin_amd64.tar.gz"
      sha256 "9f32032532f0b87376dbe63f1d8cfa6a3a3108e9cf5feb28eda1a18f5ed1ef0a"
    end
    on_arm do
      url "https://github.com/armstrongl/nd/releases/download/v#{version}/nd_#{version}_darwin_arm64.tar.gz"
      sha256 "9b6701ba3e802c745a299daa0e15fe0b18044f65b1536753decd4353a9da8fd9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/armstrongl/nd/releases/download/v#{version}/nd_#{version}_linux_amd64.tar.gz"
      sha256 "c81765a39f78a753c07882418855d053871df5eb34b5638f72832a69fc5d7606"
    end
    on_arm do
      url "https://github.com/armstrongl/nd/releases/download/v#{version}/nd_#{version}_linux_arm64.tar.gz"
      sha256 "9ccac2be2caffc294d627d78d0911d5ce34f31e08eb3c4c4e8b7f33309602fd3"
    end
  end

  # No zap stanza required
end
