# This file was generated by GoReleaser. DO NOT EDIT.
cask "nd" do
  version "0.4.0"

  on_macos do
    on_intel do
      url "https://github.com/armstrongl/nd/releases/download/v#{version}/nd_#{version}_darwin_amd64.tar.gz"
      sha256 "f16a7d9b7d7304515a688c7d8b6d3f055ffcab60df605b093c47babb58f61661"
    end
    on_arm do
      url "https://github.com/armstrongl/nd/releases/download/v#{version}/nd_#{version}_darwin_arm64.tar.gz"
      sha256 "aed90b184d5beaa4b3bf8e096061822a4a44607ff928ce15f4f199615303d0e1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/armstrongl/nd/releases/download/v#{version}/nd_#{version}_linux_amd64.tar.gz"
      sha256 "7ad00ac744040cfce9030458b09084b108f207a6880d1c9135befd9fd97dc65f"
    end
    on_arm do
      url "https://github.com/armstrongl/nd/releases/download/v#{version}/nd_#{version}_linux_arm64.tar.gz"
      sha256 "394b95a1fa100498687db9c2aa6b32e6e6f51107ca0658698e9630abfe84ff6f"
    end
  end

  name "nd"
  desc "Coding agent asset management CLI tool"
  homepage "https://github.com/armstrongl/nd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nd"

  # No zap stanza required

end
