# This file was generated by GoReleaser. DO NOT EDIT.
cask "rulebound" do
  name "rulebound"
  desc "Generate static style guide websites from Vale linting packages"
  homepage "https://github.com/armstrongl/rulebound"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rulebound"

  on_macos do
    on_intel do
      url "https://github.com/armstrongl/rulebound/releases/download/v#{version}/rulebound_#{version}_darwin_amd64.tar.gz"
      sha256 "f11a36323a18c3d7ba646743d2547e7119ce7ea27be001153fb4e42894486b76"
    end
    on_arm do
      url "https://github.com/armstrongl/rulebound/releases/download/v#{version}/rulebound_#{version}_darwin_arm64.tar.gz"
      sha256 "b2f1e8cc17115142f509fafbecbcd279d6c813727feef16cc050b341396cd349"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/armstrongl/rulebound/releases/download/v#{version}/rulebound_#{version}_linux_amd64.tar.gz"
      sha256 "26bc215b7504f4ebf1f9d6633627783e20d91ad85a3a5e29fa6ca2006264c8a4"
    end
    on_arm do
      url "https://github.com/armstrongl/rulebound/releases/download/v#{version}/rulebound_#{version}_linux_arm64.tar.gz"
      sha256 "c618d31f9ce8f50946f43e2c168f1831153d1238dd52ca05a6d583dd06c686d3"
    end
  end

  # No zap stanza required
end
